// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('PruebasFrontBuscador', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('PruebasFrontBuscador', async function() {
    await driver.get("http://localhost:3000/inventario")
    await driver.manage().window().setRect({ width: 1936, height: 1056 })
    settimeout(3000)
    await driver.findElement(By.id("AAAAAAAAAAHG")).click()
    settimeout(3000)
    await driver.findElement(By.id("search-input-1")).click()
    await driver.findElement(By.id("search-input-1")).sendKeys("aceite repsol")
    settimeout(3000)
    if (await driver.findElement(By.id("12")).getText()  == "Aceite repsol" ) {
      settimeout(3000)
      await driver.close()
    } else {
      throw error();

    }
   
  
  })
})



function settimeout (tiempo) {
  let a = 0
  while (a < (tiempo* 1000000)) a++
}